export const PlayerAtionTypes = {
    FETCH_PLAYERS_DETAILS: "FETCH_PLAYERS_DETAILS",
    FETCH_PLAYERS_DETAILS_SUCCESS: "FETCH_PLAYERS_DETAILS_SUCCESS",
    FETCH_PLAYERS_DETAILS_FAILURE: "FETCH_PLAYERS_DETAILS_FAILURE",


    SAVE_PLAYER_DETAIL: "SAVE_PLAYER_DETAIL",
    SAVE_PLAYER_DETAIL_SUCCESS: "SAVE_PLAYER_DETAIL_SUCCESS",
    SAVE_PLAYER_DETAIL_FAILURE: "SAVE_PLAYER_DETAIL_FAILURE",
};